fs.makeDir('os/')
fs.makeDir('os/games')
fs.makeDir('os/programs')
fs.makeDir('os/users')
fs.makeDir('os/programs/noteslua')
fs.makeDir('os/programs/notestxt')
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/startup.lua")
handle = download.readAll()
download.close()
file = fs.open("startup.lua","w")
file.write(handle)
file.close()
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/os/programs/run.lua")
handle = download.readAll()
download.close()
file = fs.open("os/programs/run.lua","w")
file.write(handle)
file.close()
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/os/accountmanager.lua")
handle = download.readAll()
download.close()
file = fs.open("os/accountmanager.lua","w")
file.write(handle)
file.close()
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/os/changepasswords.lua")
handle = download.readAll()
download.close()
file = fs.open("os/changepasswords.lua","w")
file.write(handle)
file.close()
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/os/command.lua")
handle = download.readAll()
download.close()
file = fs.open("os/command.lua","w")
file.write(handle)
file.close()
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/os/createaccount.lua")
handle = download.readAll()
download.close()
file = fs.open("os/createaccount.lua","w")
file.write(handle)
file.close()
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/os/deleteaccount.lua")
handle = download.readAll()
download.close()
file = fs.open("os/deleteaccount.lua","w")
file.write(handle)
file.close()
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/os/diskinstall.lua")
handle = download.readAll()
download.close()
file = fs.open("os/diskinstall.lua","w")
file.write(handle)
file.close()
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/os/encryptionapi.lua")
handle = download.readAll()
download.close()
file = fs.open("os/encryptionapi.lua","w")
file.write(handle)
file.close()
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/os/games.lua")
handle = download.readAll()
download.close()
file = fs.open("os/games.lua","w")
file.write(handle)
file.close()
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/os/info.lua")
handle = download.readAll()
download.close()
file = fs.open("os/info.lua","w")
file.write(handle)
file.close()
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/os/install.lua")
handle = download.readAll()
download.close()
file = fs.open("os/install.lua","w")
file.write(handle)
file.close()
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/os/listaccounts.lua")
handle = download.readAll()
download.close()
file = fs.open("os/listaccounts.lua","w")
file.write(handle)
file.close()
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/os/login.lua")
handle = download.readAll()
download.close()
file = fs.open("os/login.lua","w")
file.write(handle)
file.close()
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/os/main.lua")
handle = download.readAll()
download.close()
file = fs.open("os/main.lua","w")
file.write(handle)
file.close()
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/os/osapi.lua")
handle = download.readAll()
download.close()
file = fs.open("os/osapi.lua","w")
file.write(handle)
file.close()
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/os/programs.lua")
handle = download.readAll()
download.close()
file = fs.open("os/programs.lua","w")
file.write(handle)
file.close()
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/os/uninstall.lua")
handle = download.readAll()
download.close()
file = fs.open("os/uninstall.lua","w")
file.write(handle)
file.close()
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/os//games/game.lua")
handle = download.readAll()
download.close()
file = fs.open("os//games/game.lua","w")
file.write(handle)
file.close()
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/os//programs/chatroom.lua")
handle = download.readAll()
download.close()
file = fs.open("os//programs/chatroom.lua","w")
file.write(handle)
file.close()
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/os//programs/notes.lua")
handle = download.readAll()
download.close()
file = fs.open("os//programs/notes.lua","w")
file.write(handle)
file.close()
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/os//programs/noteslua/editnotes.lua")
handle = download.readAll()
download.close()
file = fs.open("os//programs/noteslua/editnotes.lua","w")
file.write(handle)
file.close()
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/os//programs/noteslua/listnotes.lua")
handle = download.readAll()
download.close()
file = fs.open("os//programs/noteslua/listnotes.lua","w")
file.write(handle)
file.close()
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/os//programs/noteslua/readnotes.lua")
handle = download.readAll()
download.close()
file = fs.open("os//programs/noteslua/readnotes.lua","w")
file.write(handle)
file.close()
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/os//users/guest.lua")
handle = download.readAll()
download.close()
file = fs.open("os//users/guest.lua","w")
file.write(handle)
file.close()
download = http.get("https://raw.github.com/Dilonq/SpaghettiOS/main/os//users/root.lua")
handle = download.readAll()
download.close()
file = fs.open("os//users/root.lua","w")
file.write(handle)
file.close()
